/**
 * Problems generated by DeviceMonitor
 *
 * @author herbert
 *
 */
package org.opendaylight.mwtn.deviceMonitor.impl;

import org.opendaylight.mwtn.base.internalTypes.InternalSeverity;

public enum DeviceMonitorProblems {

    notConnected(InternalSeverity.Warning),
    noConnectionMediator(InternalSeverity.Minor),
    noConnectionNe(InternalSeverity.Critical);

    InternalSeverity severity;

    DeviceMonitorProblems(InternalSeverity severity) {
        this.severity = severity;
    }

    InternalSeverity getSeverity() {
        return severity;
    }

}

