
#ifndef _H_y_MicrowaveModel_ObjectClasses_EthernetContainer
#define _H_y_MicrowaveModel_ObjectClasses_EthernetContainer
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    Yuma SIL header
    module MicrowaveModel-ObjectClasses-EthernetContainer
    revision 2016-09-02
    namespace uri:onf:MicrowaveModel-ObjectClasses-EthernetContainer
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "status.h"
#include "val.h"

#ifdef __cplusplus
extern "C" {
#endif

#define y_MicrowaveModel_ObjectClasses_EthernetContainer_M_MicrowaveModel_ObjectClasses_EthernetContainer (const xmlChar *)"MicrowaveModel-ObjectClasses-EthernetContainer"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_R_MicrowaveModel_ObjectClasses_EthernetContainer (const xmlChar *)"2016-09-02"

#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_MW_EthernetContainer_Pac (const xmlChar *)"MW_EthernetContainer_Pac"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_administrativeState (const xmlChar *)"administrativeState"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_bundlingIsAvail (const xmlChar *)"bundlingIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_containerID (const xmlChar *)"containerID"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_cryptographicKey (const xmlChar *)"cryptographicKey"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_currentPerformanceDataList (const xmlChar *)"currentPerformanceDataList"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_currentProblemList (const xmlChar *)"currentProblemList"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_elapsedTime (const xmlChar *)"elapsedTime"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_encryptionIsAvail (const xmlChar *)"encryptionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_encryptionIsOn (const xmlChar *)"encryptionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerCapability (const xmlChar *)"ethernetContainerCapability"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerConfiguration (const xmlChar *)"ethernetContainerConfiguration"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerCurrentPerformance (const xmlChar *)"ethernetContainerCurrentPerformance"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerCurrentProblems (const xmlChar *)"ethernetContainerCurrentProblems"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerHistoricalPerformances (const xmlChar *)"ethernetContainerHistoricalPerformances"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ethernetContainerStatus (const xmlChar *)"ethernetContainerStatus"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_granularityPeriod (const xmlChar *)"granularityPeriod"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_historicalPerformanceDataList (const xmlChar *)"historicalPerformanceDataList"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_historyDataId (const xmlChar *)"historyDataId"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ipv4CompressionIsAvail (const xmlChar *)"ipv4CompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ipv4CompressionIsOn (const xmlChar *)"ipv4CompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ipv6CompressionIsAvail (const xmlChar *)"ipv6CompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_ipv6CompressionIsOn (const xmlChar *)"ipv6CompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_lastStatusChange (const xmlChar *)"lastStatusChange"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_layer2CompressionIsAvail (const xmlChar *)"layer2CompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_layer2CompressionIsOn (const xmlChar *)"layer2CompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_layer4CompressionIsAvail (const xmlChar *)"layer4CompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_layer4CompressionIsOn (const xmlChar *)"layer4CompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_layerProtocol (const xmlChar *)"layerProtocol"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_mplsCompressionIsAvail (const xmlChar *)"mplsCompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_mplsCompressionIsOn (const xmlChar *)"mplsCompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_nameBinding (const xmlChar *)"nameBinding"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_objectClass (const xmlChar *)"objectClass"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_packetCompressionIsAvail (const xmlChar *)"packetCompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_packetCompressionIsOn (const xmlChar *)"packetCompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_performanceData (const xmlChar *)"performanceData"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_periodEndTime (const xmlChar *)"periodEndTime"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_problemKindName (const xmlChar *)"problemKindName"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_problemKindSeverity (const xmlChar *)"problemKindSeverity"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_problemKindSeverityList (const xmlChar *)"problemKindSeverityList"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_problemName (const xmlChar *)"problemName"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_problemSeverity (const xmlChar *)"problemSeverity"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_qInQCompressionIsAvail (const xmlChar *)"qInQCompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_qInQCompressionIsOn (const xmlChar *)"qInQCompressionIsOn"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_scannerId (const xmlChar *)"scannerId"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_segmentIdRef (const xmlChar *)"segmentIdRef"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_segmentsIDList (const xmlChar *)"segmentsIDList"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_sequenceNumber (const xmlChar *)"sequenceNumber"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_structureIdRef (const xmlChar *)"structureIdRef"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_supportedAlarms (const xmlChar *)"supportedAlarms"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_suspectIntervalFlag (const xmlChar *)"suspectIntervalFlag"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_timePeriod (const xmlChar *)"timePeriod"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_timeStamp (const xmlChar *)"timeStamp"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_timestamp (const xmlChar *)"timestamp"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_txEthernetBytesMaxM (const xmlChar *)"txEthernetBytesMaxM"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_txEthernetBytesMaxS (const xmlChar *)"txEthernetBytesMaxS"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_txEthernetBytesSum (const xmlChar *)"txEthernetBytesSum"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_vlanCompressionIsAvail (const xmlChar *)"vlanCompressionIsAvail"
#define y_MicrowaveModel_ObjectClasses_EthernetContainer_N_vlanCompressionIsOn (const xmlChar *)"vlanCompressionIsOn"
/********************************************************************
* FUNCTION y_MicrowaveModel_ObjectClasses_EthernetContainer_init
* 
* initialize the MicrowaveModel-ObjectClasses-EthernetContainer server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_MicrowaveModel_ObjectClasses_EthernetContainer_init (
    const xmlChar *modname,
    const xmlChar *revision);

/********************************************************************
* FUNCTION y_MicrowaveModel_ObjectClasses_EthernetContainer_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t y_MicrowaveModel_ObjectClasses_EthernetContainer_init2 (void);

/********************************************************************
* FUNCTION y_MicrowaveModel_ObjectClasses_EthernetContainer_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
extern void y_MicrowaveModel_ObjectClasses_EthernetContainer_cleanup (void);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerStatus_mro (val_value_t *parentval);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_timeStamp_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemName_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemSeverity_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_granularityPeriod_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_administrativeState_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_elapsedTime_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_timestamp_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_mro (val_value_t *parentval);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);
status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get (ses_cb_t *scb, getcb_mode_t cbmode, const val_value_t *virval, val_value_t *dstval);

status_t MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_mro (val_value_t *parentval);


#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif