../bin/callbacks_MicrowaveModel-ObjectClasses-MwConnection.o: \
 callbacks_MicrowaveModel-ObjectClasses-MwConnection.c \
 callbacks_MicrowaveModel-ObjectClasses-MwConnection.h \
 /usr/include/yuma/ncx/status.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../../utils/../utils/utils.h \
 /usr/include/yuma/platform/procdefs.h
