/*
 * dvm_runtime_callbacks.h
 *
 *  Created on: Aug 19, 2016
 *      Author: compila
 */

#ifndef DVM_RUNTIME_CALLBACKS_H_
#define DVM_RUNTIME_CALLBACKS_H_

#include "status.h"
#include "val.h"
#include "utils.h"

/*
 * module: MicrowaveModel-ObjectClasses-AirInterface
 */
char* dvm_cb_get_runtime_airInterfaceStatus_txFrequencyCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_rxFrequencyCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_txLevelCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_rxLevelCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_modulationCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_informationRateCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_snirCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_xpdCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_rfTempCur(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_lastStatusChange(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_radioPowerIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_linkIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_xpicIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_mimoIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_alicIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_atpcIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_autoFreqSelectIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_loopBackIsUp(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_localEndPointId(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_airInterfaceStatus_remoteEndPointId(char* layerProtocolKeyString);

status_t dvm_cb_get_all_air_interface_current_problem_list_keys(char *air_interface_pac_key, char** current_problem_list_key_entries, int* num_of_keys);

char* dvm_cb_get_runtime_airInterfaceCurrentProblemList_problem_timeStamp(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_airInterfaceCurrentProblemList_problem_problemName(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_airInterfaceCurrentProblemList_problem_problemSeverity(char* layerProtocolKeyString, int sequenceNumberKey);

status_t dvm_cb_get_all_air_interface_current_performance_list_keys(char *air_interface_pac_key, char **current_performance_data_list_keys_entries, int *num_of_keys);

char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_granularityPeriod(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_administrativeState(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_suspectIntervalFlag(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_elapsedTime(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_timestamp(char* layerProtocolKeyString, char* scannerIdKeyString);

char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_es(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_ses(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_cses(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_unavailability(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_txLevelMin(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_txLevelMax(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_txLevelAvg(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rxLevelMin(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rxLevelMax(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rxLevelAvg(char* layerProtocolKeyString, char* scannerIdKeyString);

char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time2Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time4SymbolsS(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time4Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time8Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time16SymbolsS(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time16Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time32Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time64Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time128Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time256Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time512Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time512SymbolsL(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time1024Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time1024SymbolsL(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time2048Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time2048SymbolsL(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time4096Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time4096SymbolsL(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time8192Symbols(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_time8192SymbolsL(char* layerProtocolKeyString, char* scannerIdKeyString);

char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_snirMin(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_snirMax(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_snirAvg(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_xpdMin(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_xpdMax(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_xpdAvg(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rfTempMin(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rfTempMax(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_rfTempAvg(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_defectBlocksSum(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_airInterfaceCurrentPerformance_currentPerformanceDataList_timePeriod(char* layerProtocolKeyString, char* scannerIdKeyString);

status_t dvm_cb_get_all_air_interface_historical_performance_list_keys(char *air_interface_pac_key, char **historical_performance_data_list_keys_entries, int *num_of_keys);


char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_periodEndTime(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_granularityPeriod(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag(char* layerProtocolKeyString, char* historyDataIdKeyString);

char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_es(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_ses(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_cses(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_unavailability(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_txLevelMin(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_txLevelMax(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_txLevelAvg(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rxLevelMin(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rxLevelMax(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rxLevelAvg(char* layerProtocolKeyString, char* historyDataIdKeyString);

char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time2Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time4SymbolsS(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time4Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time8Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time16SymbolsS(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time16Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time32Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time64Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time128Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time256Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time512Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time512SymbolsL(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time1024Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time1024SymbolsL(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time2048Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time2048SymbolsL(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time4096Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time4096SymbolsL(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time8192Symbols(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_time8192SymbolsL(char* layerProtocolKeyString, char* historyDataIdKeyString);

char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_snirMin(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_snirMax(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_snirAvg(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_xpdMin(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_xpdMax(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_xpdAvg(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rfTempMin(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rfTempMax(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_rfTempAvg(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_defectBlocksSum(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_airInterfaceHistoricalPerformances_historicalPerformanceDataList_performanceData_timePeriod(char* layerProtocolKeyString, char* historyDataIdKeyString);


/*
 * module: MicrowaveModel-ObjectClasses-PureEthernetStructure
 */
char* dvm_cb_get_runtime_pureEthernetStructureStatus_segmentStatusTypeId(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_pureEthernetStructureStatus_segmentIsReservedForTdm(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_pureEthernetStructureStatus_operationalStatus(char* layerProtocolKeyString);
char* dvm_cb_get_runtime_pureEthernetStructureStatus_lastStatusChange(char* layerProtocolKeyString);

status_t dvm_cb_get_all_pure_eth_structure_current_problem_list_keys(char *pure_eth_structure_pac_key, char** current_problem_list_key_entries, int* num_of_keys);

char* dvm_cb_get_runtime_pureEthernetStructureCurrentProblemList_problem_timeStamp(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_pureEthernetStructureCurrentProblemList_problem_problemName(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_pureEthernetStructureCurrentProblemList_problem_problemSeverity(char* layerProtocolKeyString, int sequenceNumberKey);

/*
 * module: MicrowaveModel-ObjectClasses-EthernetContainer
 */
char* dvm_cb_get_runtime_ethernetContainerStatus_lastStatusChange(char* layerProtocolKeyString);

status_t dvm_cb_get_all_ethernet_container_current_problem_list_keys(char *ethernet_container_pac_key, char** current_problem_list_key_entries, int* num_of_keys);

char* dvm_cb_get_runtime_ethernetContainerCurrentProblem_timeStamp(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_ethernetContainerCurrentProblem_problemName(char* layerProtocolKeyString, int sequenceNumberKey);
char* dvm_cb_get_runtime_ethernetContainerCurrentProblem_problemSeverity(char* layerProtocolKeyString, int sequenceNumberKey);

status_t dvm_cb_get_all_ethernet_container_current_performance_list_keys(char *ethernet_container_pac_key, char **current_performance_data_list_keys_entries, int *num_of_keys);

char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_granularityPeriod(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_administrativeState(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_suspectIntervalFlag(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_elapsedTime(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_timestamp(char* layerProtocolKeyString, char* scannerIdKeyString);

char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_txEthernetBytesMaxS(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_txEthernetBytesMaxM(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_txEthernetBytesSum(char* layerProtocolKeyString, char* scannerIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerCurrentPerformance_timePeriod(char* layerProtocolKeyString, char* scannerIdKeyString);

status_t dvm_cb_get_all_ethernet_container_historical_performance_list_keys(char *ethernet_container_pac_key, char **historical_performance_data_list_keys_entries, int *num_of_keys);

char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_periodEndTime(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_granularityPeriod(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_suspectIntervalFlag(char* layerProtocolKeyString, char* historyDataIdKeyString);

char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_txEthernetBytesMaxS(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_txEthernetBytesMaxM(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_txEthernetBytesSum(char* layerProtocolKeyString, char* historyDataIdKeyString);
char* dvm_cb_get_runtime_ethernetContainerHistoricalPerformances_timePeriod(char* layerProtocolKeyString, char* historyDataIdKeyString);

#endif /* DVM_RUNTIME_CALLBACKS_H_ */
