
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    User SIL module
    module MicrowaveModel-ObjectClasses-PureEthernetStructure
    revision 2016-09-02
    namespace uri:onf:MicrowaveModel-ObjectClasses-PureEthernetStructure
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "status.h"
#include "u_microwave-model.h"
#include "y_microwave-model.h"

#include "utils.h"
#include "ses.h"
#include "rpc.h"
#include "runtime_callbacks.h"
#include "boot_time_callbacks.h"
#include "configuration_callbacks.h"

/* put your static variables here */

#undef VAL_INT16
#define VAL_INT16(V)   ((V)->v.num.i)


static void key_free (xmlChar** keys_list, int num_of_entries)
{
    while(num_of_entries--)
    {
        free(keys_list[num_of_entries]);
    }
}

static status_t attach_supported_tdm_structure_type_list_entry(val_value_t *parentval, const xmlChar *key_entry)
{
    status_t res = NO_ERR;

    /*
     * Creating supported-tdm-structure-types-list list entry
     */
    val_value_t  *supported_tdm_structure_types_list_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_supported_tdm_structure_types_list,
            parentval,
            &supported_tdm_structure_types_list_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == supported_tdm_structure_types_list_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_supported_tdm_structure_types_list);

    /*
     * Creating tdm-structure-name leaf
     */
    val_value_t  *tdm_structure_name_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_tdm_structure_name,
            supported_tdm_structure_types_list_val,
            &tdm_structure_name_val,
            key_entry,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == tdm_structure_name_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_tdm_structure_name);

    obj_template_t *next_obj = NULL;
    next_obj = obj_next_child(obj_find_child(supported_tdm_structure_types_list_val->obj,
            y_microwave_model_M_microwave_model,
            y_microwave_model_N_tdm_structure_name));

    /*
     * Create all other leafs after transmissionModeId
     */
    res = create_and_init_siblings(next_obj,
            supported_tdm_structure_types_list_val,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");

    return NO_ERR;
}

static status_t attach_hybrid_structure_supported_tdm_structure_type_list(val_value_t *parentval)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_TDM_STRUCTURE_TYPES_ENTRIES];
    int num_of_keys;
    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol_key = VAL_STRING(agt_get_key_value(parentval, &lastkey));

    res = key_get_all_tdm_structure_name_list_keys(k_mw_hybrid_structure_pac_layer_protocol_key, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "key_get_all_tdm_structure_name_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_supported_tdm_structure_type_list_entry(parentval, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_supported_tdm_structure_type_list_entry failed for layer-protocol=%s and tdm-structure-name=%s!",
                k_mw_hybrid_structure_pac_layer_protocol_key, keys_list[i]);
    }

    key_free(keys_list, num_of_keys);

    return NO_ERR;
}

static status_t attach_hybrid_structure_capability_container(val_value_t *parentval)
{
    status_t res = NO_ERR;

    /*
     * Creating structure-id leaf
     */
    val_value_t  *structureId_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_structure_id,
            parentval,
            &structureId_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == structureId_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_structure_id);

    /*
     * Creating supported-tdm-structure-types-list list
     */
    res = attach_hybrid_structure_supported_tdm_structure_type_list(parentval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                    "attach_hybrid_structure_supported_tdm_structure_type_list failed!");

    /*
     * Create all other leafs after structure-id
     */
    obj_template_t *next_obj = NULL;
    next_obj = obj_next_child(obj_find_child(parentval->obj,
            y_microwave_model_M_microwave_model,
            y_microwave_model_N_structure_id));

    res = create_and_init_siblings(next_obj,
            parentval,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");


    return NO_ERR;

}

static status_t attach_hybrid_structure_structure_type_container(val_value_t *parentval)
{
    status_t res = NO_ERR;

    /*
     * Creating structure-type container entry
     */
    val_value_t  *structure_type_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_structure_type,
            parentval,
            &structure_type_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == structure_type_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_structure_type);

    /*
     * Creating tdm-structure-name leaf
     */
    val_value_t  *tdm_structure_name_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_tdm_structure_name,
            structure_type_val,
            &tdm_structure_name_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == tdm_structure_name_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_tdm_structure_name);

    obj_template_t *next_obj = NULL;
    next_obj = obj_next_child(obj_find_child(structure_type_val->obj,
            y_microwave_model_M_microwave_model,
            y_microwave_model_N_tdm_structure_name));

    /*
     * Create all other leafs after tdm-structure-name
     */
    res = create_and_init_siblings(next_obj,
            structure_type_val,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");

    return NO_ERR;
}

static status_t attach_problem_kind_severity_list_entry(val_value_t* parentval, const xmlChar* problem_kind_severity_list_key_entry)
{
    status_t res = NO_ERR;

    /*
     * Creating problem-kind-severity-list list entry
     */
    val_value_t  *problem_kind_severity_list_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_problem_kind_severity_list,
            parentval,
            &problem_kind_severity_list_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == problem_kind_severity_list_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_problem_kind_severity_list);

    /*
     * Creating problem-kind-name leaf
     */
    val_value_t  *problem_kind_name_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_problem_kind_name,
            problem_kind_severity_list_val,
            &problem_kind_name_val,
            problem_kind_severity_list_key_entry,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == problem_kind_name_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_problem_kind_name);

    /*
     * Creating problem-kind-severity leaf
     */
    val_value_t  *problem_kind_severity_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_problem_kind_severity,
            problem_kind_severity_list_val,
            &problem_kind_severity_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == problem_kind_severity_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_problem_kind_severity);

    return NO_ERR;
}

static status_t attach_problem_kind_severity_list(val_value_t* parentval)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_PROBLEM_KIND_SEVERITY_ENTRIES];
    int num_of_keys;

    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol_key = VAL_STRING(agt_get_key_value(parentval, &lastkey));

    res = key_get_all_hybrid_structure_problem_kind_severity_list_keys(k_mw_hybrid_structure_pac_layer_protocol_key, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "key_get_all_hybrid_structure_problem_kind_severity_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_problem_kind_severity_list_entry(parentval, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free (keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_problem_kind_severity_list_entry failed for layer_protocol=%s and key=%s!", k_mw_hybrid_structure_pac_layer_protocol_key, keys_list[i]);
     }
    key_free (keys_list, num_of_keys);

    return NO_ERR;
}

static status_t attach_hybrid_structure_configuration_container(val_value_t *parentval)
{
    status_t res = NO_ERR;

    /*
     * Creating structure-type container
     */
    res = attach_hybrid_structure_structure_type_container(parentval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                    "attach_hybrid_structure_structure_type_container failed!");

    /*
     * Creating number-of-tdm-segments-to-be-reserved leaf
     */
    val_value_t  *number_of_tdm_segments_to_be_reserved_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_number_of_tdm_segments_to_be_reserved,
            parentval,
            &number_of_tdm_segments_to_be_reserved_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == number_of_tdm_segments_to_be_reserved_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_number_of_tdm_segments_to_be_reserved);

    /*
     * Creating problem-kind-severity-list list
     */
    res = attach_problem_kind_severity_list(parentval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "attach_hybrid_structure_problem_kind_severity_list failed!");

    return NO_ERR;
}

static status_t attach_segment_status_list_entry(val_value_t *parentval, const xmlChar *key_entry)
{
    status_t res = NO_ERR;

    /*
     * Creating segment-status-list list entry
     */
    val_value_t  *segment_status_list_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_segment_status_list,
            parentval,
            &segment_status_list_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == segment_status_list_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_segment_status_list);

    /*
     * Creating segment-status-type-id leaf
     */
    val_value_t  *segment_status_type_id_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_segment_status_type_id,
            segment_status_list_val,
            &segment_status_type_id_val,
            key_entry,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == segment_status_type_id_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_segment_status_type_id);

    obj_template_t *next_obj = NULL;
    next_obj = obj_next_child(obj_find_child(segment_status_list_val->obj,
            y_microwave_model_M_microwave_model,
            y_microwave_model_N_segment_status_type_id));

    /*
     * Create all other leafs after transmissionModeId
     */
    res = create_and_init_siblings(next_obj,
            segment_status_list_val,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");

    return NO_ERR;
}

static status_t get_hybrid_structure_segment_status_list(ses_cb_t *scb,
        getcb_mode_t cbmode,
        val_value_t *vir_val,
        val_value_t *dst_val)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_SEGMENT_STATUS_LIST_ENTRIES];
    int num_of_keys;
    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol_key = VAL_STRING(agt_get_key_value(dst_val, &lastkey));

    res = key_get_all_segment_status_list_keys(k_mw_hybrid_structure_pac_layer_protocol_key, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "key_get_all_segment_status_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_segment_status_list_entry(dst_val, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_segment_status_list_entry failed for layer-protocol=%s and tdm-structure-name=%s!",
                k_mw_hybrid_structure_pac_layer_protocol_key, keys_list[i]);
    }

    key_free(keys_list, num_of_keys);

    /*
     * Creating last-status-change leaf
     */
    val_value_t  *last_status_change_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_last_status_change,
            dst_val,
            &last_status_change_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == last_status_change_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_last_status_change);

    return NO_ERR;
}



static status_t attach_hybrid_structure_status_container(val_value_t *parentval)
{
    status_t res = NO_ERR;

    /*
     * Creating segment-status-list list
     */
    val_init_virtual(parentval,
                     get_hybrid_structure_segment_status_list,
                     parentval->obj);
    return NO_ERR;
}


static status_t attach_hybrid_structure_current_problem_list_entry(val_value_t* parentval, const xmlChar* hybrid_structure_current_problem_list_key_entry)
{
    status_t res = NO_ERR;

    /*
     * Create currentProblemList list entry
     */

    val_value_t  *currentProblemList_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_current_problem_list,
            parentval,
            &currentProblemList_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == currentProblemList_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_current_problem_list);

    /*
     * Create sequenceNumber leaf
     */
    val_value_t  *sequenceNumber_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_sequence_number,
            currentProblemList_val,
            &sequenceNumber_val,
            hybrid_structure_current_problem_list_key_entry,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == sequenceNumber_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_sequence_number);

    /*
     * Create problemName virtual leaf with callback attached
     */
    val_value_t  *problemName_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_problem_name,
            currentProblemList_val,
            &problemName_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == problemName_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_problem_name);

    /*
     * Create timeStamp virtual leaf with callback attached
     */
    val_value_t  *timeStamp_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_time_stamp,
            currentProblemList_val,
            &timeStamp_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == timeStamp_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_time_stamp);

    /*
     * Create problemSeverity virtual leaf with callback attached
     */
    val_value_t  *problemSeverity_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_problem_severity,
            currentProblemList_val,
            &problemSeverity_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == problemSeverity_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_problem_severity);

    return NO_ERR;
}

static status_t get_hybrid_structure_current_problem_list(ses_cb_t *scb, getcb_mode_t cbmode, val_value_t *vir_val, val_value_t *dst_val)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_HYBRID_STRUCTURE_CURRENT_PROBLEM_LIST_ENTRIES];
    int num_of_keys;

    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol = VAL_STRING(agt_get_key_value(dst_val, &lastkey));

    res = key_get_all_hybrid_structure_current_problem_list_keys(k_mw_hybrid_structure_pac_layer_protocol, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "key_get_all_hybrid_structure_current_problem_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_hybrid_structure_current_problem_list_entry(dst_val, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_hybrid_structure_hybrid_structure_current_problem_list_keys_entriescurrent_problem_list_entry failed for key=%s!", keys_list[i]);
    }

    key_free(keys_list, num_of_keys);

    return NO_ERR;
}

static status_t attach_hybrid_structure_current_performance_list_entry(val_value_t *parentval, const char *key_entry)
{
    status_t res = NO_ERR;

    /*
     * Create current-performance-data-list list entry
     */
    val_value_t  *current_performance_data_list_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_current_performance_data_list,
            parentval,
            &current_performance_data_list_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == current_performance_data_list_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_current_performance_data_list);

    /*
     * Create scanner-id leaf
     */
    val_value_t  *scanner_id_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_scanner_id,
            current_performance_data_list_val,
            &scanner_id_val,
            key_entry,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == scanner_id_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_scanner_id);

    /*
     * Create performance-data virtual leaf with callback attached
     */
    val_value_t  *performance_data_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_performance_data,
            current_performance_data_list_val,
            &performance_data_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == performance_data_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_performance_data);

    /*
     * Create timestamp virtual leaf with callback attached
     */
    val_value_t  *timestamp_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_timestamp,
            current_performance_data_list_val,
            &timestamp_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == timestamp_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_timestamp);

    /*
     * Create suspect-interval-flag virtual leaf with callback attached
     */
    val_value_t  *suspect_interval_flag_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_suspect_interval_flag,
            current_performance_data_list_val,
            &suspect_interval_flag_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == suspect_interval_flag_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_suspect_interval_flag);

    /*
     * Create elapsed-time virtual leaf with callback attached
     */
    val_value_t  *elapsed_time_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_elapsed_time,
            current_performance_data_list_val,
            &elapsed_time_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == elapsed_time_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_elapsed_time);

    /*
     * Create granularity-period virtual leaf with callback attached
     */
    val_value_t  *granularity_period_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_granularity_period,
            current_performance_data_list_val,
            &granularity_period_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == granularity_period_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_granularity_period);

    /*
     * Create administrative-state virtual leaf with callback attached
     */
    val_value_t  *administrative_state_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_administrative_state,
            current_performance_data_list_val,
            &administrative_state_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == administrative_state_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_administrative_state);

    /*
     * Create object-class virtual leaf with callback attached
     */

    val_value_t  *object_class_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_object_class,
            current_performance_data_list_val,
            &object_class_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == object_class_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_object_class);

    /*
     * Create name-binding virtual leaf with callback attached
     */

    val_value_t  *name_binding_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_name_binding,
            current_performance_data_list_val,
            &name_binding_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == name_binding_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_name_binding);

    return NO_ERR;
}

static status_t get_hybrid_structure_current_performance_list(ses_cb_t *scb,
        getcb_mode_t cbmode,
        val_value_t *vir_val,
        val_value_t *dst_val)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_HYBRID_STRUCTURE_CURRENT_PERFORMANCE_LIST_ENTRIES];
    int num_of_keys;

    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol_key = VAL_STRING(agt_get_key_value(dst_val, &lastkey));

    YUMA_ASSERT(TRUE, NOP, "get_hybrid_structure_current_performance_list was called!");

    res = key_get_all_hybrid_structure_current_performance_list_keys(k_mw_hybrid_structure_pac_layer_protocol_key, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_get_all_hybrid_structure_current_performance_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_hybrid_structure_current_performance_list_entry(dst_val, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_hybrid_structure_current_performance_list_entry failed for key=%s!", keys_list[i]);
    }

    key_free(keys_list, num_of_keys);

    return NO_ERR;
}

static status_t attach_hybrid_structure_historical_performance_list_entry(val_value_t *parentval, const char *key_entry)
{
    status_t res = NO_ERR;

    /*
     * Create historical-performance-data-list list entry
     */
    val_value_t  *historical_performance_data_list_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_historical_performance_data_list,
            parentval,
            &historical_performance_data_list_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == historical_performance_data_list_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_historical_performance_data_list);

    /*
     * Create history-data-id leaf
     */
    val_value_t  *history_data_id_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_history_data_id,
            historical_performance_data_list_val,
            &history_data_id_val,
            key_entry,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == history_data_id_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_history_data_id);

    /*
     * Create performance-data virtual leaf with callback attached
     */
    val_value_t  *performance_data_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_performance_data,
            historical_performance_data_list_val,
            &performance_data_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == performance_data_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_performance_data);

    /*
     * Create suspect-interval-flag virtual leaf with callback attached
     */
    val_value_t  *suspect_interval_flag_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_suspect_interval_flag,
            historical_performance_data_list_val,
            &suspect_interval_flag_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == suspect_interval_flag_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_suspect_interval_flag);

    /*
     * Create period-end-time virtual leaf with callback attached
     */
    val_value_t  *period_end_time_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_period_end_time,
            historical_performance_data_list_val,
            &period_end_time_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == period_end_time_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_period_end_time);

    /*
     * Create granularity-period virtual leaf with callback attached
     */
    val_value_t  *granularity_period_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_granularity_period,
            historical_performance_data_list_val,
            &granularity_period_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == granularity_period_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_granularity_period);

    /*
     * Create object-class virtual leaf with callback attached
     */

    val_value_t  *object_class_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_object_class,
            historical_performance_data_list_val,
            &object_class_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == object_class_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_object_class);

    /*
     * Create name-binding virtual leaf with callback attached
     */

    val_value_t  *name_binding_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_name_binding,
            historical_performance_data_list_val,
            &name_binding_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == name_binding_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_name_binding);

    return NO_ERR;
}

static status_t get_hybrid_structure_historical_performance_list(ses_cb_t *scb,
        getcb_mode_t cbmode,
        val_value_t *vir_val,
        val_value_t *dst_val)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_HYBRID_STRUCTURE_CURRENT_PERFORMANCE_LIST_ENTRIES];
    int num_of_keys;

    val_value_t *lastkey = NULL;
    const xmlChar *k_mw_hybrid_structure_pac_layer_protocol_key = VAL_STRING(agt_get_key_value(dst_val, &lastkey));

    YUMA_ASSERT(TRUE, NOP, "get_hybrid_structure_historical_performance_list was called!");

    res = key_get_all_hybrid_structure_historical_performance_list_keys(k_mw_hybrid_structure_pac_layer_protocol_key, keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_get_all_hybrid_structure_current_performance_list_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        res = attach_hybrid_structure_historical_performance_list_entry(dst_val, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL,
                "attach_hybrid_structure_current_performance_list_entry failed for key=%s!", keys_list[i]);
    }

    key_free(keys_list, num_of_keys);

    return NO_ERR;
}

static status_t attach_hybrid_structure_element_to_running_config(cfg_template_t* runningcfg, const xmlChar* air_hybrid_structure_key)
{
    status_t res = NO_ERR;

    /*
     * Creating the root element for the module: mw-hybrid-structure-pac
     */
    val_value_t *mw_hybrid_structure_pac_val = NULL;

    res = create_root_element_for_module(y_microwave_model_M_microwave_model,
            y_microwave_model_R_microwave_model,
            y_microwave_model_N_mw_hybrid_mw_structure_pac,
            &mw_hybrid_structure_pac_val);
    YUMA_ASSERT(NULL == mw_hybrid_structure_pac_val, return ERR_INTERNAL_VAL ,
            "create_root_element_for_module failed for element=%s", y_microwave_model_N_mw_hybrid_mw_structure_pac);

    val_add_child(mw_hybrid_structure_pac_val, runningcfg->root);

    /*
     * Creating the layer-protocol element
     */
    val_value_t  *layer_protocol_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_layer_protocol,
            mw_hybrid_structure_pac_val,
            &layer_protocol_val,
            air_hybrid_structure_key,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == layer_protocol_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_layer_protocol);

    /*
     * Creating hybrid-structure-capability container
     */
    val_value_t  *hybrid_structure_capability_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_hybrid_mw_structure_capability,
            mw_hybrid_structure_pac_val,
            &hybrid_structure_capability_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == hybrid_structure_capability_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_hybrid_mw_structure_capability);

    /*
     * Creating all the leaf elements of the hybrid-structure-capability container
     */
    res = attach_hybrid_structure_capability_container(hybrid_structure_capability_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                    "attach_hybrid_structure_capability_container failed for layer_protocol=%s", air_hybrid_structure_key);

    /*
     * Creating hybrid-structure-configuration container
     */
    val_value_t  *hybrid_structure_configuration_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_hybrid_mw_structure_configuration,
            mw_hybrid_structure_pac_val,
            &hybrid_structure_configuration_val,
            NULL,
            y_microwave_model_M_microwave_model,
            false);
    YUMA_ASSERT(NULL == hybrid_structure_configuration_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_hybrid_mw_structure_configuration);

    res = attach_hybrid_structure_configuration_container(hybrid_structure_configuration_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                    "attach_hybrid_structure_configuration_container failed for layer_protocol=%s", air_hybrid_structure_key);

    /*
     * Creating hybrid-structure-status container
     */
    val_value_t  *hybrid_structure_status_val = NULL;

    res = create_and_init_child_element(y_microwave_model_M_microwave_model,
            y_microwave_model_N_hybrid_mw_structure_status,
            mw_hybrid_structure_pac_val,
            &hybrid_structure_status_val,
            NULL,
            y_microwave_model_M_microwave_model,
            true);
    YUMA_ASSERT(NULL == hybrid_structure_status_val, return ERR_INTERNAL_VAL ,
                "create_and_init_child_element failed for element=%s", y_microwave_model_N_hybrid_mw_structure_status);

    res = attach_hybrid_structure_status_container(hybrid_structure_status_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                    "attach_hybrid_structure_configuration_status failed");
    /*
     * Creating hybrid-structure-current-problems container
     */
    val_value_t *hybrid_structure_current_problems_val = NULL;

    res = agt_add_container(y_microwave_model_M_microwave_model,
            y_microwave_model_N_hybrid_mw_structure_current_problems,
            mw_hybrid_structure_pac_val,
            &hybrid_structure_current_problems_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                        "agt_make_container failed for obj=%s", y_microwave_model_N_hybrid_mw_structure_current_problems);

    val_init_virtual(hybrid_structure_current_problems_val,
                    get_hybrid_structure_current_problem_list,
                    hybrid_structure_current_problems_val->obj);

    /*
     * Creating hybrid-structure-current-performance container
     */
    val_value_t  *hybrid_structure_current_performance_val = NULL;

    res = agt_add_container(y_microwave_model_M_microwave_model,
            y_microwave_model_N_hybrid_mw_structure_current_performance,
            mw_hybrid_structure_pac_val,
            &hybrid_structure_current_performance_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                        "agt_make_container failed for obj=%s", y_microwave_model_N_hybrid_mw_structure_current_performance);

    val_init_virtual(hybrid_structure_current_performance_val,
                    get_hybrid_structure_current_performance_list,
                    hybrid_structure_current_performance_val->obj);

    /*
      * Creating hybrid-structure-historical-performance container
      */
     val_value_t  *hybrid_structure_historical_performance_val = NULL;

     res = agt_add_container(y_microwave_model_M_microwave_model,
             y_microwave_model_N_hybrid_mw_structure_historical_performances,
             mw_hybrid_structure_pac_val,
             &hybrid_structure_historical_performance_val);
     YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                         "agt_make_container failed for obj=%s", y_microwave_model_N_hybrid_mw_structure_historical_performances);

     val_init_virtual(hybrid_structure_historical_performance_val,
                     get_hybrid_structure_historical_performance_list,
                     hybrid_structure_historical_performance_val->obj);

    return NO_ERR;
}

static status_t build_attributes_tree_and_attach_to_running_cfg(cfg_template_t* runningcfg)
{
    status_t res = NO_ERR;
    xmlChar* keys_list[MAX_NUMBER_OF_HYBRID_STRUCTURE_ENTRIES];
    int num_of_keys;

    /*
     * Getting all the interfaces of the system
     */
    res = key_get_all_hybrid_structure_pac_keys(keys_list, &num_of_keys);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "key_get_all_hybrid_structure_pac_keys failed!");

    for (int i=0; i<num_of_keys; ++i)
    {
        /*
         * Attaching a mw_hybrid_structure_pac list entry
         */
        res = attach_hybrid_structure_element_to_running_config(runningcfg, keys_list[i]);
        YUMA_ASSERT(res != NO_ERR, key_free(keys_list, num_of_keys); return ERR_INTERNAL_VAL, "attach_hybrid_structure_element_to_running_config failed!");
    }

    key_free(keys_list, num_of_keys);

    return NO_ERR;
}

status_t build_hybrid_structure_attributes_tree (void)
{
    status_t res = NO_ERR;

    /*
     * Creating the running datastore
     */
    cfg_template_t* runningcfg;
    runningcfg = cfg_get_config_id(NCX_CFGID_RUNNING);
    YUMA_ASSERT(!runningcfg || !runningcfg->root, return ERR_INTERNAL_VAL, "No running config available in u_microwave_model_init2!");

    /*
     * Creating the mw-hybrid-structure-pac list and attach it to the running config
     */
    res = build_attributes_tree_and_attach_to_running_cfg(runningcfg);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "Could not build the tree for the running config");

    return res;
} /* u_microwave_model_init2 */
