/*
 * utils.h
 *
 *  Created on: Mar 22, 2016
 *      Author: compila
 */

#ifndef YANG_MODULES_MICROWAVEMODEL_OBJECTCLASSES_MWCONNECTION_SRC_UTILS_H_
#define YANG_MODULES_MICROWAVEMODEL_OBJECTCLASSES_MWCONNECTION_SRC_UTILS_H_

#include <stdio.h>

#define NOP

#define YUMA_ASSERT(condition, action, fmt, ...) 	\
({													\
	if ((condition))								\
	{												\
		log_debug("\nMW PoC: %s at %s line %d: "fmt, __FILE__,__FUNCTION__,__LINE__, ##__VA_ARGS__); \
		action;										\
	} 												\
})

typedef enum
{
	NETWORK_ELEMENT,
	LOGICAL_TERMINATION_POINT,
	LAYER_PROTOCOL
} type_of_element;

typedef enum
{
	MWPS_TTP,
	MWS_TTP,
	ETH_CTP
} ltp_type;

#define MAX_NUMBER_OF_AIR_INTERFACE_PAC 100
#define MAX_NUMBER_OF_STRUCTURE_PAC 100
#define MAX_NUMBER_OF_CONTAINER_PAC 100

#define MAX_NUMBER_OF_AIR_INTERFACE_CAPABILITY_LIST_KEYS 100
#define MAX_NUMBER_OF_SCRIPT_LIST_KEYS 100

#define MAX_NUMBER_OF_TIME_SLOTS 1000

#define MAX_NUMBER_OF_PROBLEMS 30

#define TIME_SLOT_CAPACITY 2048 //2048 kbps

#define MAX_NUMBER_OF_CONTAINER_TYPE_KEYS 100
#define MAX_NUMBER_OF_CONTAINER_CONFIG_TIME_SLOT_ID_KEYS 1000
#define MAX_NUMBER_OF_STRUCTURE_IDs 100

#define MAX_NUMBER_OF_LTPs 100

#define LTP_MWPS_PREFIX "LTP-MWPS-TTP-"
#define LTP_MWS_PREFIX "LTP-MWS-TTP-"
#define LP_MWPS_PREFIX "LP-MWPS-TTP-"
#define LP_MWS_PREFIX "LP-MWS-TTP-"
#define MWPS_STRING "MWPS"
#define MWS_STRING "MWS"
#define LTP_ETH_CTP_PREFIX "LTP-ETH-CTP-"
#define LP_ETH_CTP_PREFIX "LP-ETH-CTP-"
#define ETH_CTP_STRING "ETH-CTP"

#endif /* YANG_MODULES_MICROWAVEMODEL_OBJECTCLASSES_MWCONNECTION_SRC_UTILS_H_ */
