../bin/callbacks_CoreModel-CoreNetworkModule-ObjectClasses.o: \
 callbacks_CoreModel-CoreNetworkModule-ObjectClasses.c \
 callbacks_CoreModel-CoreNetworkModule-ObjectClasses.h \
 /usr/include/yuma/ncx/status.h /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h ../../utils/../utils/utils.h \
 /usr/include/yuma/platform/procdefs.h
