
#ifndef _H_u_MicrowaveModel_ObjectClasses_EthernetContainer
#define _H_u_MicrowaveModel_ObjectClasses_EthernetContainer
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    User SIL header
    module MicrowaveModel-ObjectClasses-EthernetContainer
    revision 2016-09-02
    namespace uri:onf:MicrowaveModel-ObjectClasses-EthernetContainer
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "agt.h"
#include "agt_cb.h"
#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "y_MicrowaveModel-ObjectClasses-EthernetContainer.h"

#ifdef __cplusplus
extern "C" {
#endif

/* container /MW_EthernetContainer_Pac/ethernetContainerCapability */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCapability_ {
    boolean bundlingIsAvail;
    boolean packetCompressionIsAvail;
    boolean layer2CompressionIsAvail;
    boolean vlanCompressionIsAvail;
    boolean qInQCompressionIsAvail;
    boolean mplsCompressionIsAvail;
    boolean ipv4CompressionIsAvail;
    boolean ipv6CompressionIsAvail;
    boolean layer4CompressionIsAvail;
    boolean encryptionIsAvail;
    xmlChar *supportedAlarms;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCapability;

/* list /MW_EthernetContainer_Pac/ethernetContainerConfiguration/segmentsIDList */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_ {
    dlq_hdr_t qhdr;
    xmlChar *structureIdRef;
    int16 segmentIdRef;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList;

/* list /MW_EthernetContainer_Pac/ethernetContainerConfiguration/problemKindSeverityList */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_ {
    dlq_hdr_t qhdr;
    xmlChar *problemKindName;
    xmlChar *problemKindSeverity;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList;

/* container /MW_EthernetContainer_Pac/ethernetContainerConfiguration */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration_ {
    xmlChar *containerID;
    dlq_hdr_t segmentsIDList;
    boolean packetCompressionIsOn;
    boolean layer2CompressionIsOn;
    boolean vlanCompressionIsOn;
    boolean qInQCompressionIsOn;
    boolean mplsCompressionIsOn;
    boolean ipv4CompressionIsOn;
    boolean ipv6CompressionIsOn;
    boolean layer4CompressionIsOn;
    boolean encryptionIsOn;
    xmlChar *cryptographicKey;
    dlq_hdr_t problemKindSeverityList;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration;

/* container /MW_EthernetContainer_Pac/ethernetContainerStatus */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerStatus_ {
    xmlChar *lastStatusChange;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerStatus;

/* list /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems/currentProblemList */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_ {
    dlq_hdr_t qhdr;
    int32 sequenceNumber;
    xmlChar *timeStamp;
    xmlChar *problemName;
    xmlChar *problemSeverity;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList;

/* container /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_ {
    dlq_hdr_t currentProblemList;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems;

/* container /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/performanceData */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_ {
    int32 txEthernetBytesMaxS;
    int64 txEthernetBytesMaxM;
    int64 txEthernetBytesSum;
    int32 timePeriod;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData;

/* list /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_ {
    dlq_hdr_t qhdr;
    xmlChar *objectClass;
    xmlChar *nameBinding;
    xmlChar *scannerId;
    xmlChar *granularityPeriod;
    xmlChar *administrativeState;
    boolean suspectIntervalFlag;
    int32 elapsedTime;
    xmlChar *timestamp;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData performanceData;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList;

/* container /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_ {
    dlq_hdr_t currentPerformanceDataList;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance;

/* container /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/performanceData */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_ {
    int32 txEthernetBytesMaxS;
    int64 txEthernetBytesMaxM;
    int64 txEthernetBytesSum;
    int32 timePeriod;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData;

/* list /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_ {
    dlq_hdr_t qhdr;
    xmlChar *objectClass;
    xmlChar *nameBinding;
    xmlChar *historyDataId;
    xmlChar *periodEndTime;
    xmlChar *granularityPeriod;
    boolean suspectIntervalFlag;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData performanceData;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList;

/* container /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_ {
    dlq_hdr_t historicalPerformanceDataList;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances;

/* list /MW_EthernetContainer_Pac */
typedef struct y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ {
    dlq_hdr_t qhdr;
    xmlChar *layerProtocol;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCapability ethernetContainerCapability;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerConfiguration ethernetContainerConfiguration;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerStatus ethernetContainerStatus;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems ethernetContainerCurrentProblems;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance ethernetContainerCurrentPerformance;
    y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances ethernetContainerHistoricalPerformances;
} y_MicrowaveModel_ObjectClasses_EthernetContainer_T_MW_EthernetContainer_Pac;

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_layerProtocol_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/layerProtocol
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_layerProtocol_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_bundlingIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/bundlingIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_bundlingIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_packetCompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/packetCompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_packetCompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_layer2CompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/layer2CompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_layer2CompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_vlanCompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/vlanCompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_vlanCompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_qInQCompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/qInQCompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_qInQCompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_mplsCompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/mplsCompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_mplsCompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_ipv4CompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/ipv4CompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_ipv4CompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_ipv6CompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/ipv6CompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_ipv6CompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_layer4CompressionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/layer4CompressionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_layer4CompressionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_encryptionIsAvail_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/encryptionIsAvail
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_encryptionIsAvail_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_supportedAlarms_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCapability/supportedAlarms
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCapability_supportedAlarms_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_containerID_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/containerID
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_containerID_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_structureIdRef_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/segmentsIDList/structureIdRef
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_structureIdRef_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_structureIdRef,
    int16 k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_segmentIdRef);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_segmentIdRef_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/segmentsIDList/segmentIdRef
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_segmentIdRef_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_structureIdRef,
    int16 k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_segmentIdRef);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/segmentsIDList
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_structureIdRef,
    int16 k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_segmentsIDList_segmentIdRef);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_packetCompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/packetCompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_packetCompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_layer2CompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/layer2CompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_layer2CompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_vlanCompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/vlanCompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_vlanCompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_qInQCompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/qInQCompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_qInQCompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_mplsCompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/mplsCompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_mplsCompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_ipv4CompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/ipv4CompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_ipv4CompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_ipv6CompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/ipv6CompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_ipv6CompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_layer4CompressionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/layer4CompressionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_layer4CompressionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_encryptionIsOn_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/encryptionIsOn
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_encryptionIsOn_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_cryptographicKey_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/cryptographicKey
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_cryptographicKey_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindName_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/problemKindSeverityList/problemKindName
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindName_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindName);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindSeverity_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/problemKindSeverityList/problemKindSeverity
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindSeverity_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindName);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration/problemKindSeverityList
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerConfiguration_problemKindSeverityList_problemKindName);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerConfiguration
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerConfiguration_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerStatus_lastStatusChange_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerStatus/lastStatusChange
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerStatus_lastStatusChange_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems/currentProblemList/sequenceNumber
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    int32 k_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_timeStamp_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems/currentProblemList/timeStamp
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_timeStamp_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    int32 k_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemName_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems/currentProblemList/problemName
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemName_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    int32 k_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemSeverity_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentProblems/currentProblemList/problemSeverity
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_problemSeverity_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    int32 k_MW_EthernetContainer_Pac_ethernetContainerCurrentProblems_currentProblemList_sequenceNumber);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_objectClass_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/objectClass
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_objectClass_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_nameBinding_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/nameBinding
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_nameBinding_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/scannerId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_granularityPeriod_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/granularityPeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_granularityPeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_administrativeState_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/administrativeState
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_administrativeState_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/suspectIntervalFlag
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_elapsedTime_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/elapsedTime
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_elapsedTime_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_timestamp_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/timestamp
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_timestamp_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesMaxS_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/performanceData/txEthernetBytesMaxS
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesMaxS_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesMaxM_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/performanceData/txEthernetBytesMaxM
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesMaxM_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesSum_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/performanceData/txEthernetBytesSum
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_txEthernetBytesSum_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_timePeriod_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerCurrentPerformance/currentPerformanceDataList/performanceData/timePeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_performanceData_timePeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerCurrentPerformance_currentPerformanceDataList_scannerId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_objectClass_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/objectClass
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_objectClass_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_nameBinding_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/nameBinding
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_nameBinding_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/historyDataId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/periodEndTime
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/granularityPeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/suspectIntervalFlag
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesMaxS_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/performanceData/txEthernetBytesMaxS
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesMaxS_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesMaxM_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/performanceData/txEthernetBytesMaxM
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesMaxM_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesSum_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/performanceData/txEthernetBytesSum
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_txEthernetBytesSum_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_timePeriod_get
* 
* Get database object callback
* Path: /MW_EthernetContainer_Pac/ethernetContainerHistoricalPerformances/historicalPerformanceDataList/performanceData/timePeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_performanceData_timePeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol,
    const xmlChar *k_MW_EthernetContainer_Pac_ethernetContainerHistoricalPerformances_historicalPerformanceDataList_historyDataId);


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_edit
* 
* Edit database object callback
* Path: /MW_EthernetContainer_Pac
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_MW_EthernetContainer_Pac_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_EthernetContainer_Pac_layerProtocol);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_init
* 
* initialize the MicrowaveModel-ObjectClasses-EthernetContainer server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_init (
    const xmlChar *modname,
    const xmlChar *revision);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
extern status_t u_MicrowaveModel_ObjectClasses_EthernetContainer_init2 (void);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_EthernetContainer_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
extern void u_MicrowaveModel_ObjectClasses_EthernetContainer_cleanup (void);

#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif