
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump 2.5-5

    User SIL module
    module MicrowaveModel-ObjectClasses-PureEthernetStructure
    revision 2016-09-02
    namespace uri:onf:MicrowaveModel-ObjectClasses-PureEthernetStructure
    organization ONF (Open Networking Foundation) Open Transport Working Group - Wireless Transport Project

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_cb.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "status.h"
#include "u_MicrowaveModel-ObjectClasses-PureEthernetStructure.h"
#include "y_MicrowaveModel-ObjectClasses-PureEthernetStructure.h"

#include "utils.h"
#include "ses.h"
#include "rpc.h"
#include "runtime_callbacks.h"
#include "configuration_callbacks.h"

/* put your static variables here */

#undef VAL_INT16
#define VAL_INT16(V)   ((V)->v.num.i)


static status_t build_attributes_tree_and_attach_to_running_cfg(cfg_template_t* runningcfg);
static status_t attach_air_pure_eth_structure_element_to_running_config(cfg_template_t* runningcfg, const char* air_pure_eth_structure_key);

static status_t attach_pure_eth_structure_capability_container(val_value_t *parentval);

static status_t attach_pure_eth_structure_configuration_container(val_value_t *parentval);
static status_t attach_problem_kind_severity_list(val_value_t* parentval);
static status_t attach_problem_kind_severity_list_entry(val_value_t* parentval, const char* problem_kind_severity_list_key_entry);
static status_t attach_air_interface_current_performance_list_entry(val_value_t *parentval, const char *air_interface_current_performance_list_key_entry);

static status_t get_pure_eth_structure_current_problem_list(ses_cb_t *scb, getcb_mode_t cbmode, val_value_t *vir_val, val_value_t *dst_val);
static status_t attach_current_problem_list_entry(val_value_t* parentval, const char* pure_eth_structure_current_problem_list_key_entry);

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_layerProtocol_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac/layerProtocol
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_layerProtocol_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_layerProtocol_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_layerProtocol_edit */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_structureId_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCapability/structureId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_structureId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    const xmlChar *structureId;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_structureId_get callback");
    }


    /* set the structureId var here, change EMPTY_STRING */
    structureId = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        structureId);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_structureId_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_supportedAlarms_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCapability/supportedAlarms
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_supportedAlarms_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    const xmlChar *supportedAlarms;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_supportedAlarms_get callback");
    }


    /* set the supportedAlarms var here, replace (void) or use default value */
    (void)supportedAlarms;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        (const xmlChar *)"Supported alarms not yet defined.");

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCapability_supportedAlarms_get */


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureConfiguration/problemKindSeverityList/problemKindName
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        res = cb_send_to_device_pureEthernetStructureConfiguration_problemKindSeverityList_element_value((newval) ? newval : curval, k_MW_PureEthernetStructure_Pac_layerProtocol, k_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName);
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName_edit */


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindSeverity_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureConfiguration/problemKindSeverityList/problemKindSeverity
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindSeverity_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindSeverity_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        res = cb_send_to_device_pureEthernetStructureConfiguration_problemKindSeverityList_element_value((newval) ? newval : curval, k_MW_PureEthernetStructure_Pac_layerProtocol, k_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName);
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindSeverity_edit */


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureConfiguration/problemKindSeverityList
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_problemKindName)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_problemKindSeverityList_edit */


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureConfiguration
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureConfiguration_edit */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentStatusTypeId_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureStatus/segmentStatusList/segmentStatusTypeId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentStatusTypeId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    int16 segmentStatusTypeId;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentStatusTypeId_get callback");
    }

    res = cb_set_runtime_pureEthernetStructure_element_value(&dstval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_set_runtime_pureEthernetStructure_element_value failed for element %s", dstval->name);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentStatusTypeId_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentIsReservedForTdm_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureStatus/segmentStatusList/segmentIsReservedForTdm
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentIsReservedForTdm_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    boolean segmentIsReservedForTdm;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentIsReservedForTdm_get callback");
    }

    res = cb_set_runtime_pureEthernetStructure_element_value(&dstval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_set_runtime_pureEthernetStructure_element_value failed for element %s", dstval->name);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_segmentIsReservedForTdm_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_operationalStatus_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureStatus/segmentStatusList/operationalStatus
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_operationalStatus_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    const xmlChar *operationalStatus;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_operationalStatus_get callback");
    }

    res = cb_set_runtime_pureEthernetStructure_element_value(&dstval);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_set_runtime_pureEthernetStructure_element_value failed for element %s", dstval->name);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_segmentStatusList_operationalStatus_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_lastStatusChange_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureStatus/lastStatusChange
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_lastStatusChange_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;
    const xmlChar *lastStatusChange;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_lastStatusChange_get callback");
    }

    res = cb_set_runtime_pureEthernetStructure_element_value(&dstval);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_set_runtime_pureEthernetStructure_element_value failed for element %s", dstval->name);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_lastStatusChange_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentProblems/currentProblemList/sequenceNumber
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    int32 k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber)
{
    status_t res = NO_ERR;
    int32 sequenceNumber;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber_get callback");
    }


    /* set the sequenceNumber var here, change zero */
    sequenceNumber = 0;
    VAL_INT(dstval) = sequenceNumber;

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_timeStamp_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentProblems/currentProblemList/timeStamp
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_timeStamp_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    int32 k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber)
{
    status_t res = NO_ERR;
    const xmlChar *timeStamp;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_timeStamp_get callback");
    }


    /* set the timeStamp var here, change EMPTY_STRING */
    timeStamp = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        timeStamp);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_timeStamp_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemName_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentProblems/currentProblemList/problemName
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemName_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    int32 k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber)
{
    status_t res = NO_ERR;
    const xmlChar *problemName;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemName_get callback");
    }


    /* set the problemName var here, replace (void) or use default value */
    (void)problemName;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        (const xmlChar *)"Structure problems not yet defined.");

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemName_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemSeverity_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentProblems/currentProblemList/problemSeverity
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemSeverity_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    int32 k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_sequenceNumber)
{
    status_t res = NO_ERR;
    const xmlChar *problemSeverity;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemSeverity_get callback");
    }


    /* set the problemSeverity var here, replace (void) or use default value */
    (void)problemSeverity;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        (const xmlChar *)"warning");

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentProblems_currentProblemList_problemSeverity_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_objectClass_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/objectClass
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_objectClass_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *objectClass;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_objectClass_get callback");
    }


    /* set the objectClass var here, change EMPTY_STRING */
    objectClass = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        objectClass);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_objectClass_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_nameBinding_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/nameBinding
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_nameBinding_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *nameBinding;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_nameBinding_get callback");
    }


    /* set the nameBinding var here, change EMPTY_STRING */
    nameBinding = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        nameBinding);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_nameBinding_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/scannerId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *scannerId;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId_get callback");
    }


    /* set the scannerId var here, change EMPTY_STRING */
    scannerId = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        scannerId);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_granularityPeriod_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/granularityPeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_granularityPeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *granularityPeriod;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_granularityPeriod_get callback");
    }


    /* set the granularityPeriod var here, change enum */
    granularityPeriod = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        granularityPeriod);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_granularityPeriod_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_administrativeState_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/administrativeState
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_administrativeState_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *administrativeState;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_administrativeState_get callback");
    }


    /* set the administrativeState var here, change enum */
    administrativeState = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        administrativeState);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_administrativeState_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/suspectIntervalFlag
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    boolean suspectIntervalFlag;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get callback");
    }


    /* set the suspectIntervalFlag var here, replace (void) or use default value */
    (void)suspectIntervalFlag;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        (const xmlChar *)"false");

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_suspectIntervalFlag_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_elapsedTime_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/elapsedTime
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_elapsedTime_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    int32 elapsedTime;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_elapsedTime_get callback");
    }


    /* set the elapsedTime var here, change zero */
    elapsedTime = 0;
    VAL_INT(dstval) = elapsedTime;

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_elapsedTime_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_timestamp_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/timestamp
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_timestamp_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    const xmlChar *timestamp;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_timestamp_get callback");
    }


    /* set the timestamp var here, change EMPTY_STRING */
    timestamp = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        timestamp);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_timestamp_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_performanceData_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureCurrentPerformance/currentPerformanceDataList/performanceData
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_performanceData_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_scannerId)
{
    status_t res = NO_ERR;
    int32 performanceData;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_performanceData_get callback");
    }


    /* set the performanceData var here, change zero */
    performanceData = 0;
    VAL_INT(dstval) = performanceData;

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureCurrentPerformance_currentPerformanceDataList_performanceData_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_objectClass_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/objectClass
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_objectClass_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    const xmlChar *objectClass;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_objectClass_get callback");
    }


    /* set the objectClass var here, change EMPTY_STRING */
    objectClass = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        objectClass);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_objectClass_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_nameBinding_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/nameBinding
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_nameBinding_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    const xmlChar *nameBinding;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_nameBinding_get callback");
    }


    /* set the nameBinding var here, change EMPTY_STRING */
    nameBinding = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        nameBinding);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_nameBinding_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/historyDataId
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    const xmlChar *historyDataId;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId_get callback");
    }


    /* set the historyDataId var here, change EMPTY_STRING */
    historyDataId = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        historyDataId);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/periodEndTime
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    const xmlChar *periodEndTime;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get callback");
    }


    /* set the periodEndTime var here, change EMPTY_STRING */
    periodEndTime = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        periodEndTime);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_periodEndTime_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/granularityPeriod
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    const xmlChar *granularityPeriod;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get callback");
    }


    /* set the granularityPeriod var here, change enum */
    granularityPeriod = EMPTY_STRING;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        granularityPeriod);

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_granularityPeriod_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/suspectIntervalFlag
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    boolean suspectIntervalFlag;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get callback");
    }


    /* set the suspectIntervalFlag var here, replace (void) or use default value */
    (void)suspectIntervalFlag;
    res = val_set_simval_obj(
        dstval,
        dstval->obj,
        (const xmlChar *)"false");

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_suspectIntervalFlag_get */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_performanceData_get
* 
* Get database object callback
* Path: /MW_PureEthernetStructure_Pac/pureEthernetStructureHistoricalPerformances/historicalPerformanceDataList/performanceData
* Fill in 'dstval' contents
* 
* INPUTS:
*     see ncx/getcb.h for details
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_performanceData_get (
    val_value_t *dstval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol,
    const xmlChar *k_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_historyDataId)
{
    status_t res = NO_ERR;
    int32 performanceData;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_performanceData_get callback");
    }


    /* set the performanceData var here, change zero */
    performanceData = 0;
    VAL_INT(dstval) = performanceData;

    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureHistoricalPerformances_historicalPerformanceDataList_performanceData_get */


/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_edit
* 
* Edit database object callback
* Path: /MW_PureEthernetStructure_Pac
* Add object instrumentation in COMMIT phase.
* 
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_edit */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init
* 
* initialize the MicrowaveModel-ObjectClasses-PureEthernetStructure server instrumentation library
* 
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    ncx_module_t *MicrowaveModel_ObjectClasses_PureEthernetStructure_mod = NULL;

#ifdef u_MicrowaveModel_ObjectClasses_PureEthernetStructure_F_pure_ethernet
    ncx_set_feature_enable(
        y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
        (const xmlChar *)"pure-ethernet",
        TRUE);
#else
    ncx_set_feature_enable(
        y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
        (const xmlChar *)"pure-ethernet",
        FALSE);
#endif

    MicrowaveModel_ObjectClasses_PureEthernetStructure_mod = ncx_find_module(
        y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
        y_MicrowaveModel_ObjectClasses_PureEthernetStructure_R_MicrowaveModel_ObjectClasses_PureEthernetStructure);
    if (MicrowaveModel_ObjectClasses_PureEthernetStructure_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }
    /* put your module initialization code here */
    
    return res;
} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init2
* 
* SIL init phase 2: non-config data structures
* Called after running config is loaded
* 
* RETURNS:
*     error status
********************************************************************/
status_t u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init2 (void)
{
    status_t res = NO_ERR;


	/*
	 * Creating the running datastore
	 */
    cfg_template_t* runningcfg;
	runningcfg = cfg_get_config_id(NCX_CFGID_RUNNING);
	YUMA_ASSERT(!runningcfg || !runningcfg->root, return ERR_INTERNAL_VAL, "No running config available in u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init2!");

	/*
	 * Creating the MW_PureEthernetStructure_Pac list and attach it to the running config
	 */
	res = build_attributes_tree_and_attach_to_running_cfg(runningcfg);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "Could not build the tree for the running config");

    return res;
} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_init2 */

/********************************************************************
* FUNCTION u_MicrowaveModel_ObjectClasses_PureEthernetStructure_cleanup
*    cleanup the server instrumentation library
* 
********************************************************************/
void u_MicrowaveModel_ObjectClasses_PureEthernetStructure_cleanup (void)
{
    /* put your cleanup code here */
    
} /* u_MicrowaveModel_ObjectClasses_PureEthernetStructure_cleanup */

/* END u_MicrowaveModel_ObjectClasses_PureEthernetStructure.c */
static status_t build_attributes_tree_and_attach_to_running_cfg(cfg_template_t* runningcfg)
{
	status_t res = NO_ERR;
    char* air_pure_eth_structure_keys_list[MAX_NUMBER_OF_PURE_ETHERNET_STRUCTURE_ENTRIES];
    int num_of_pure_eth_structure_pac_keys;

	/*
	 * Getting all the interfaces of the system
	 */
	res = cb_get_all_pure_eth_structure_pac_keys(air_pure_eth_structure_keys_list, &num_of_pure_eth_structure_pac_keys);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_get_all_air_pure_eth_structure_keys failed!");

	for (int i=0; i<num_of_pure_eth_structure_pac_keys; ++i)
	{
		/*
		 * Attaching a MW_PureEthernetStructure_Pac list entry
		 */
		res = attach_air_pure_eth_structure_element_to_running_config(runningcfg, air_pure_eth_structure_keys_list[i]);
		YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "attach_air_pure_eth_structure_element_to_running_config failed!");
	}

	return NO_ERR;
}

static status_t attach_air_pure_eth_structure_element_to_running_config(cfg_template_t* runningcfg, const char* air_pure_eth_structure_key)
{
	status_t res = NO_ERR;

	/*
	 * Creating the root element for the module: MW_PureEthernetStructure_Pac
	 */
	val_value_t *MW_PureEthernetStructure_Pac_val = NULL;

                                         
	res = create_root_element_for_module(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_R_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_MW_PureEthernetStructure_Pac,
			&MW_PureEthernetStructure_Pac_val);
	YUMA_ASSERT(NULL == MW_PureEthernetStructure_Pac_val, return ERR_INTERNAL_VAL ,
			"create_root_element_for_module failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_MW_PureEthernetStructure_Pac);

	val_add_child(MW_PureEthernetStructure_Pac_val, runningcfg->root);

	/*
	 * Creating the layerProtocol element
	 */
	val_value_t  *layerProtocol_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_layerProtocol,
			MW_PureEthernetStructure_Pac_val,
			&layerProtocol_val,
			air_pure_eth_structure_key,
			false);
	YUMA_ASSERT(NULL == layerProtocol_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_layerProtocol);

	/*
	 * Creating pureEthernetStructureCapability container
	 */
	val_value_t  *pureEthernetStructureCapability_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCapability,
			MW_PureEthernetStructure_Pac_val,
			&pureEthernetStructureCapability_val,
			NULL,
			false);
	YUMA_ASSERT(NULL == pureEthernetStructureCapability_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCapability);

	/*
	 * Creating all the leaf elements of the pureEthernetStructureCapability container
	 */
	res = attach_pure_eth_structure_capability_container(pureEthernetStructureCapability_val);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
					"attach_pure_eth_structure_capability_container failed for layerProtocol=%s", air_pure_eth_structure_key);

	/*
	 * Creating pureEthernetStructureConfiguration container
	 */
	val_value_t  *pureEthernetStructureConfiguration_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureConfiguration,
			MW_PureEthernetStructure_Pac_val,
			&pureEthernetStructureConfiguration_val,
			NULL,
			false);
	YUMA_ASSERT(NULL == pureEthernetStructureConfiguration_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureConfiguration);

	res = attach_pure_eth_structure_configuration_container(pureEthernetStructureConfiguration_val);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
					"attach_pure_eth_structure_configuration_container failed for layerProtocol=%s", air_pure_eth_structure_key);

	/*
	 * Creating pureEthernetStructureStatus container
	 */
	val_value_t  *pureEthernetStructureStatus_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureStatus,
			MW_PureEthernetStructure_Pac_val,
			&pureEthernetStructureStatus_val,
			NULL,
			true);
	YUMA_ASSERT(NULL == pureEthernetStructureStatus_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureStatus);


	res = MicrowaveModel_ObjectClasses_PureEthernetStructure_MW_PureEthernetStructure_Pac_pureEthernetStructureStatus_mro(pureEthernetStructureStatus_val);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
					"MicrowaveModel_ObjectClasses_AirInterface_MW_AirInterface_Pac_pureEthernetStructureStatus_mro failed");
	/*
	 * Creating pureEthernetStructureCurrentProblems container
	 */
	val_value_t *pureEthernetStructureCurrentProblems_val = NULL;

	res = agt_add_container(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCurrentProblems,
			MW_PureEthernetStructure_Pac_val,
			&pureEthernetStructureCurrentProblems_val);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
						"agt_make_container failed for obj=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCurrentProblems);

	val_init_virtual(pureEthernetStructureCurrentProblems_val,
					get_pure_eth_structure_current_problem_list,
					pureEthernetStructureCurrentProblems_val->obj);

#if 0
    /*
     * Creating pureEthernetStructureCurrentPerformance container
     */
    val_value_t  *pureEthernetStructureeCurrentPerformance_val = NULL;

    res = agt_add_container(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
        y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCurrentPerformance,
            MW_AirInterface_Pac_val,
            &pureEthernetStructureeCurrentPerformance_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                        "agt_make_container failed for obj=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_pureEthernetStructureCurrentPerformance);

    val_init_virtual(pureEthernetStructureeCurrentPerformance_val,
                     get_pure_ethernet_structure_current_performance_list,
                     pureEthernetStructureCurrentPerformance_val->obj);
    /*
     * Creating airInterfaceHistoricalPerformances_val container
     */
    val_value_t *airInterfaceHistoricalPerformances_val = NULL;

    res = agt_add_container(y_MicrowaveModel_ObjectClasses_AirInterface_M_MicrowaveModel_ObjectClasses_AirInterface,
            y_MicrowaveModel_ObjectClasses_AirInterface_N_airInterfaceHistoricalPerformances,
            MW_AirInterface_Pac_val,
            &airInterfaceHistoricalPerformances_val);
    YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL ,
                        "agt_make_container failed for obj=%s", y_MicrowaveModel_ObjectClasses_AirInterface_N_airInterfaceHistoricalPerformances);

    val_init_virtual(airInterfaceHistoricalPerformances_val,
                    get_air_interface_historical_performance_list,
                    airInterfaceHistoricalPerformances_val->obj);

#endif

	return NO_ERR;
}

static status_t attach_pure_eth_structure_capability_container(val_value_t *parentval)
{
	status_t res = NO_ERR;

	/*
	 * Creating structureId leaf
	 */
	val_value_t  *structureId_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_structureId,
			parentval,
			&structureId_val,
			NULL,
			false);
	YUMA_ASSERT(NULL == structureId_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_structureId);

	/*
	 * Create all other leafs after structureId
	 */
	obj_template_t *next_obj = NULL;
	next_obj = obj_next_child(obj_find_child(parentval->obj,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_structureId));

	res = create_and_init_siblings(next_obj, parentval, false);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");


	return NO_ERR;

}

static status_t attach_pure_eth_structure_configuration_container(val_value_t *parentval)
{
	status_t res = NO_ERR;

	/*
	 * Create all leafs
	 */

	res = attach_problem_kind_severity_list(parentval);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "attach_pure_ethernet_structure_problem_kind_severity_list failed!");

	return NO_ERR;
}

static status_t attach_problem_kind_severity_list(val_value_t* parentval)
{
	status_t res = NO_ERR;
	char* problem_kind_name_list[MAX_NUMBER_OF_PROBLEM_KIND_SEVERITY_ENTRIES];
	int num_of_problem_kind_name_keys;

	val_value_t *lastkey = NULL;
	const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol_key = VAL_STRING(agt_get_key_value(parentval, &lastkey));

	res = cb_get_all_problem_kind_severity_list_keys(k_MW_PureEthernetStructure_Pac_layerProtocol_key, problem_kind_name_list, &num_of_problem_kind_name_keys);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_get_all_problem_kind_severity_list_keys failed!");

	for (int i=0; i<num_of_problem_kind_name_keys; ++i)
	{
		res = attach_problem_kind_severity_list_entry(parentval, problem_kind_name_list[i]);
		YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL,
				"attach_problem_kind_severity_list_entry failed for layerProtocol=%s and key=%s!", k_MW_PureEthernetStructure_Pac_layerProtocol_key, problem_kind_name_list[i]);
	}

	return NO_ERR;
}

static status_t attach_problem_kind_severity_list_entry(val_value_t* parentval, const char* problem_kind_severity_list_key_entry)
{
	status_t res = NO_ERR;

	/*
	 * Creating problemKindSeverityList list entry
	 */
	val_value_t  *problemKindSeverityList_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindSeverityList,
			parentval,
			&problemKindSeverityList_val,
			NULL,
			false);
	YUMA_ASSERT(NULL == problemKindSeverityList_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindSeverityList);

	/*
	 * Creating problemKindName leaf
	 */
	val_value_t  *problemKindName_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindName,
			problemKindSeverityList_val,
			&problemKindName_val,
			problem_kind_severity_list_key_entry,
			false);
	YUMA_ASSERT(NULL == problemKindName_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindName);

	/*
	 * Creating problemKindSeverity leaf
	 */
	val_value_t  *problemKindSeverity_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindSeverity,
			problemKindSeverityList_val,
			&problemKindSeverity_val,
			NULL,
			false);
	YUMA_ASSERT(NULL == problemKindSeverity_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_problemKindSeverity);

	return NO_ERR;
}

static status_t get_pure_eth_structure_current_problem_list(ses_cb_t *scb, getcb_mode_t cbmode, val_value_t *vir_val, val_value_t *dst_val)
{
	status_t res = NO_ERR;
	char* pure_eth_structure_current_problem_list_keys_entries[MAX_NUMBER_OF_PURE_ETHERNET_STRUCTURE_CURRENT_PROBLEM_LIST_ENTRIES];
	int num_of_pure_eth_structure_current_problem_list_keys;

	val_value_t *lastkey = NULL;
	const xmlChar *k_MW_PureEthernetStructure_Pac_layerProtocol = VAL_STRING(agt_get_key_value(dst_val, &lastkey));

	res = cb_get_all_pure_eth_structure_current_problem_list_keys(k_MW_PureEthernetStructure_Pac_layerProtocol, pure_eth_structure_current_problem_list_keys_entries, &num_of_pure_eth_structure_current_problem_list_keys);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "cb_get_all_pure_eth_structure_current_problem_list_keys failed!");

	for (int i=0; i<num_of_pure_eth_structure_current_problem_list_keys; ++i)
	{
		res = attach_current_problem_list_entry(dst_val, pure_eth_structure_current_problem_list_keys_entries[i]);
		YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL,
				"attach_pure_eth_structure_current_problem_list_entry failed for key=%s!", pure_eth_structure_current_problem_list_keys_entries[i]);
	}

	return NO_ERR;
}

static status_t attach_current_problem_list_entry(val_value_t* parentval, const char* pure_eth_structure_current_problem_list_key_entry)
{
	status_t res = NO_ERR;

	/*
	 * Create currentProblemList list entry
	 */

	val_value_t  *currentProblemList_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_currentProblemList,
			parentval,
			&currentProblemList_val,
			NULL,
			true);
	YUMA_ASSERT(NULL == currentProblemList_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_currentProblemList);

	/*
	 * Create sequenceNumber leaf
	 */
	val_value_t  *sequenceNumber_val = NULL;

	res = create_and_init_child_element(y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_sequenceNumber,
			currentProblemList_val,
			&sequenceNumber_val,
			pure_eth_structure_current_problem_list_key_entry,
			true);
	YUMA_ASSERT(NULL == sequenceNumber_val, return ERR_INTERNAL_VAL ,
				"create_and_init_child_element failed for element=%s", y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_sequenceNumber);

	/*
	 * Create all other leafs after sequenceNumber
	 */
	obj_template_t *next_obj = NULL;
	next_obj = obj_next_child(obj_find_child(currentProblemList_val->obj,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_M_MicrowaveModel_ObjectClasses_PureEthernetStructure,
			y_MicrowaveModel_ObjectClasses_PureEthernetStructure_N_sequenceNumber));

	res = create_and_init_siblings(next_obj, currentProblemList_val, true);
	YUMA_ASSERT(res != NO_ERR, return ERR_INTERNAL_VAL, "create_and_init_siblings failed!");

	return NO_ERR;
}
