../bin/u_MicrowaveModel-Notifications.o: u_MicrowaveModel-Notifications.c \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlversion.h \
 /usr/include/libxml2/libxml/xmlexports.h \
 /usr/include/yuma/platform/procdefs.h /usr/include/yuma/agt/agt.h \
 /usr/include/yuma/ncx/help.h /usr/include/yuma/ncx/ncxconst.h \
 /usr/include/yuma/ncx/obj.h /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/tree.h \
 /usr/include/libxml2/libxml/xmlstring.h \
 /usr/include/libxml2/libxml/xmlregexp.h \
 /usr/include/libxml2/libxml/xmlmemory.h \
 /usr/include/libxml2/libxml/threads.h \
 /usr/include/libxml2/libxml/globals.h \
 /usr/include/libxml2/libxml/parser.h /usr/include/libxml2/libxml/dict.h \
 /usr/include/libxml2/libxml/hash.h /usr/include/libxml2/libxml/valid.h \
 /usr/include/libxml2/libxml/xmlerror.h \
 /usr/include/libxml2/libxml/list.h \
 /usr/include/libxml2/libxml/xmlautomata.h \
 /usr/include/libxml2/libxml/entities.h \
 /usr/include/libxml2/libxml/encoding.h \
 /usr/include/libxml2/libxml/xmlIO.h /usr/include/libxml2/libxml/SAX.h \
 /usr/include/libxml2/libxml/xlink.h /usr/include/libxml2/libxml/SAX2.h \
 /usr/include/yuma/ncx/grp.h /usr/include/yuma/ncx/ncxtypes.h \
 /usr/include/yuma/ncx/dlq.h /usr/include/yuma/ncx/xmlns.h \
 /usr/include/yuma/ncx/status.h /usr/include/yuma/ncx/tk.h \
 /usr/include/yuma/ncx/rpc.h /usr/include/yuma/ncx/op.h \
 /usr/include/yuma/ncx/val.h /usr/include/yuma/ncx/plock_cb.h \
 /usr/include/yuma/ncx/tstamp.h /usr/include/yuma/ncx/typ.h \
 /usr/include/yuma/ncx/xml_util.h /usr/include/libxml2/libxml/xmlreader.h \
 /usr/include/libxml2/libxml/relaxng.h \
 /usr/include/libxml2/libxml/xmlschemas.h /usr/include/yuma/ncx/xml_msg.h \
 /usr/include/yuma/ncx/log.h /usr/include/yuma/agt/agt_cb.h \
 /usr/include/yuma/agt/agt.h /usr/include/yuma/ncx/op.h \
 /usr/include/yuma/ncx/rpc.h /usr/include/yuma/ncx/ses.h \
 /usr/include/yuma/ncx/status.h /usr/include/yuma/ncx/val.h \
 /usr/include/yuma/agt/agt_not.h /usr/include/yuma/agt/agt_timer.h \
 /usr/include/yuma/agt/agt_util.h /usr/include/yuma/ncx/cfg.h \
 /usr/include/yuma/ncx/ncx.h /usr/include/yuma/ncx/yang.h \
 /usr/include/yuma/ncx/ext.h /usr/include/yuma/ncx/plock.h \
 /usr/include/yuma/ncx/xpath.h /usr/include/yuma/ncx/var.h \
 /usr/include/yuma/ncx/runstack.h /usr/include/yuma/ncx/val_util.h \
 /usr/include/yuma/ncx/getcb.h /usr/include/yuma/ncx/dlq.h \
 /usr/include/yuma/ncx/ncx.h /usr/include/yuma/ncx/ncx_feature.h \
 /usr/include/yuma/ncx/ncxmod.h /usr/include/yuma/ncx/cap.h \
 /usr/include/yuma/ncx/ncxtypes.h /usr/include/yuma/ncx/val_util.h \
 /usr/include/yuma/ncx/xml_util.h u_MicrowaveModel-Notifications.h \
 y_MicrowaveModel-Notifications.h ../../utils/../utils/utils.h
